datastax/cassandra-data-migrator

pom.xml
src/main/java/datastax/astra/migrate/DiffJobSession.java
src/resources/sparkConf.properties

DiffData (Data Validation) performance improvements (also fixes JVM heap space errors). The target queries based on primary-key were made aSync & fired in parallel.

Data Validation performance improvements

---

pom.xml
src/main/java/datastax/astra/migrate/BaseJobSession.java
src/main/java/datastax/astra/migrate/CopyJobSession.java
src/main/java/datastax/astra/migrate/DiffJobSession.java
src/main/java/datastax/astra/migrate/OriginCountJobSession.java
src/main/scala/datastax/astra/migrate/BaseJob.scala
src/resources/sparkConf.properties

Added filtering code to CopyJob. Takes a flag then proceeds to find column and value from config file and filter data from origin to target.

Added filtering code to CopyJob. 

---

.github/workflows/maven.yml
README.md
cassandra-data-migrator.iml
pom.xml
src/main/java/datastax/astra/migrate/AbstractJobSession.java
src/main/java/datastax/astra/migrate/CopyJobSession.java
src/main/scala/datastax/astra/migrate/AbstractJob.scala
src/main/scala/datastax/astra/migrate/BaseJob.scala
src/main/scala/datastax/astra/migrate/OriginData.scala
src/resources/sparkConf.properties

- Removed Astra flag
- Commented counter & filters
- Fixed varint mapping
- Fixed writetime Minor logging fixes
Fixed POSIX error

Refactorred config

---

Dockerfile

Made mvn build as part of the Dockerfile

Build inside docker

---

README.md
pom.xml
src/resources/runCommands.txt

Follow semver format

---

.github/workflows/maven.yml
pom.xml
scripts/bump_minor_version

Implement auto-pom version bump

Implement auto-pom version bump

---

pom.xml
src/main/java/datastax/astra/migrate/AbstractJobSession.java
src/main/java/datastax/astra/migrate/BaseJobSession.java
src/main/java/datastax/astra/migrate/CopyJobSession.java
src/main/java/datastax/astra/migrate/DiffJobSession.java
src/resources/sparkConf.properties

Implement [feature/issue # 86](https://github.com/datastax/cassandra-data-migrator/issues/86)

Handle blank timestamp values in primary-key columns graciously

---

README.md
pom.xml
src/main/java/datastax/astra/migrate/SplitPartitions.java
src/main/scala/datastax/astra/migrate/AbstractJob.scala
src/main/scala/datastax/astra/migrate/BaseJob.scala
src/main/scala/datastax/astra/migrate/DiffData.scala
src/main/scala/datastax/astra/migrate/Migrate.scala
src/main/scala/datastax/astra/migrate/MigratePartitionsFromFile.scala
src/main/scala/datastax/astra/migrate/MigrateRowsFromFile.scala
src/main/scala/datastax/astra/migrate/OriginData.scala
src/resources/sparkConf.properties

Renamed property splitSize to numSplits while supporting backward compatibility
Updated Readme

Renamed property splitSize to numSplits (support backward compatibility)

---

.github/workflows/cdm-integrationtest.yml
.github/workflows/maven-publish.yml
SIT/Makefile
pom.xml

Switches version to 4.0.0 and uses -SNAPSHOT builds
CDM-15
**Checklist:**

CDM-15 : enabling snapshot version

---

src/main/java/datastax/cdm/cql/statement/AbstractTargetUpsertStatement.java

CDM-36 using isAssignableFrom rather than equals

---

README.md
pom.xml
src/main/java/datastax/astra/migrate/AbstractJobSession.java
src/main/java/datastax/astra/migrate/BaseJobSession.java
src/main/java/datastax/astra/migrate/schema/TableInfo.java
src/main/java/datastax/astra/migrate/schema/TypeInfo.java
src/resources/cdm.properties

Auto discovers counter table schema & supports migration & validation of the same.
Updates new & existing counters on target correctly.
Fixes #131 
**Checklist:**

Implemented auto-discovery of counter tables

---

.github/workflows/maven-publish.yml
.gitignore

**What this PR does**: Automatically clean-up older maven packages
n/a
**Checklist:**

Automatically clean-up older maven packages

---

pom.xml
src/main/java/datastax/astra/migrate/CopyJobSession.java
src/main/java/datastax/astra/migrate/DiffJobSession.java
src/main/java/datastax/astra/migrate/schema/ColumnInfo.java
src/main/java/datastax/astra/migrate/schema/TypeInfo.java

Handles tables with no TTL & Writetime columns graciously
Fixes #154 
**Checklist:**

CDM-62 handle no TTL & Writetime graciously

---

.github/workflows/snyk-cli-scan
.github/workflows/snyk-cli-scan-pr
.gitignore
.snyk
.snyk.ignore.example

**What this PR does**: Adds snyk scans to the project
Fixes CDM-64
**Checklist:**

Add snyk scan to CI

---

README.md
src/resources/cdm-detailed.properties
src/resources/cdm.properties

create simplified version of cdm.properties

---

Dockerfile
RELEASE.md
pom.xml

**What this PR does**: Fix broken docker build
Fixes #CDM-83
**Checklist:**

CDM-83 Fix broken docker build due to stale maven link

---

src/resources/cdm-detailed.properties

Minor edits

---

RELEASE.md
SIT/features/06_partition_range/migrate_with_partitionfile.properties
SIT/features/07_migrate_rows/migrate_with_pkrowsfile.properties
src/main/java/com/datastax/cdm/properties/KnownProperties.java

**What this PR does**: Documentation changes
Fixes #CDM-88
**Checklist:**

Documentation changes

---

src/resources/cdm-detailed.properties

Add a commented out line for #spark.cdm.feature.constantColumns.types

---

pom.xml
src/main/java/datastax/astra/migrate/AbstractJobSession.java
src/main/java/datastax/astra/migrate/GuardrailJobSession.java
src/main/java/datastax/astra/migrate/schema/TableInfo.java
src/resources/cdm.properties

**What this PR does**: Implement support for custom TTL-Writetime cols in version 3.x
Fixes #CDM-90
**Checklist:**

CDM-90: Support for custom TTL-Writetime cols

---

SIT/environment.sh
SIT/smoke/04_counters/cdm.fixData.assert
SIT/smoke/04_counters/cdm.fixForce.assert
SIT/smoke/04_counters/cdm.migrateData.assert
SIT/smoke/04_counters/cdm.validateData.assert
SIT/smoke/04_counters/expected.out
SIT/smoke/04_counters/setup.cql
src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java

**What this PR does**: Handles NPE issue with counter table
Fixes #185 
**Checklist:**

CDM-91: Fix NPE issue with counter tables with null fields

---

RELEASE.md

**What this PR does**: A minor update to 4.1.3 release notes comment.
**Which issue(s) this PR fixes**: n/a
**Checklist:**

Update release notes for 4.1.3 for added clarity

---

Dockerfile

**What this PR does**: Make DSBulk version agnostic
**Checklist:**

Make DSBulk version agnostic

---

.github/workflows/cdm-integrationtest.yml
.github/workflows/maven.yml
.github/workflows/snyk-cli-scan.yml
.github/workflows/snyk-pr-cleanup.yml

**What this PR does**: CI improvements
**Checklist:**

CI concurrency improvements

---

SIT/test.sh

Makes test bash script more robust:
- uses find+mv to move files, which makes it best-effort (no failure when no source files found)
- wraps commands that involve redirects in double-quotes and executes via bash -c

Makes test.sh more robust

---

.github/workflows/dependabot.yml

**What this PR does**: Monthly check-ins to update GHA jobs packages to keep current & up to date.
**Checklist:**

[Enhancement] Monthly schedule to check for GHA job packages updates

---

.github/workflows/maven-publish.yml

**What this PR does**: Auto-delete old packages
**Checklist:**

Auto delete old packages retaining a couple

---

Dockerfile
README.md
RELEASE.md
pom.xml
rat-excludes.txt
src/resources/migrate_data.sh

**What this PR does**: Upgrade to leverage Spark `3.5.1`.
Fixes #248 
**Checklist:**
- [] Automated Tests added/updated

Upgrade to leverage Spark 3.5.1

---

pom.xml

**What this PR does**: Migrate off to Apache Cassandra Java Driver - https://github.com/apache/cassandra-java-driver
**Checklist:**

Migrate to Apache Cassandra Java Driver

---

src/main/java/com/datastax/cdm/feature/Guardrail.java
src/main/java/com/datastax/cdm/job/AbstractJobSession.java
src/main/java/com/datastax/cdm/job/BaseJobSession.java
src/main/java/com/datastax/cdm/job/CopyJobSession.java
src/main/java/com/datastax/cdm/job/DiffJobSession.java
src/main/java/com/datastax/cdm/properties/KnownProperties.java
src/resources/cdm-detailed.properties
src/resources/cdm.properties

**What this PR does**: Removed functionality related to retry
Fixes #271 
**Checklist:**

Removed functionality related to retry

---

Dockerfile
README.md
pom.xml

**What this PR does**: Bump cassandra-all and spark version bumps
n/a
**Checklist:**

Minor version bumps

---

RELEASE.md
SIT/features/01_constant_column/cdm.fixData.assert
SIT/features/01_constant_column/cdm.validateData.assert
SIT/features/02_explode_map/cdm.fixData.assert
SIT/features/02_explode_map/cdm.validateData.assert
SIT/features/03_codec/cdm.fixData.assert
SIT/features/03_codec/cdm.validateData.assert
SIT/features/04_udt_mapper/cdm.fixData.assert
SIT/features/04_udt_mapper/cdm.validateData.assert
SIT/features/05_guardrail/cdm.fixData.assert
SIT/features/05_guardrail/cdm.validateData.assert
SIT/features/06_constant_column_remove/cdm.fixData.assert
SIT/features/06_constant_column_remove/cdm.validateData.assert
SIT/features/07_constant_column_replace/cdm.fixData.assert
SIT/features/07_constant_column_replace/cdm.validateData.assert
SIT/regression/01_explode_map_with_constants/cdm.fixData.assert
SIT/regression/01_explode_map_with_constants/cdm.validateData.assert
SIT/regression/02_ColumnRenameWithConstantsAndExplode/cdm.fixData.assert
SIT/regression/02_ColumnRenameWithConstantsAndExplode/cdm.validateData.assert
SIT/regression/03_performance/cdm.fixData.assert
SIT/regression/03_performance/cdm.validateData.assert
SIT/smoke/03_ttl_writetime/cdm.fixData.assert
SIT/smoke/03_ttl_writetime/cdm.validateData.assert
SIT/smoke/04_counters/cdm.fixForce.assert
SIT/smoke/04_counters/cdm.validateData.assert
src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java
src/main/java/com/datastax/cdm/feature/TrackRun.java
src/main/java/com/datastax/cdm/job/DiffJobSession.java
src/test/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatementTest.java
src/test/java/com/datastax/cdm/feature/TrackRunTest.java

**What this PR does**: Skip corrected-diff on Validation rerun with previous-run-id
**Checklist:**

Upgraded DiffData to skip corrected-diff on rerun with previous-run-id

---

.github/workflows/snyk-cli-scan.yml
.github/workflows/snyk-pr-cleanup.yml

**What this PR does**: Just to suppress the failing snyk workflows due to no jobs available
**Checklist:**

Add a name to workflows & dummy job

---

RELEASE.md
src/main/java/com/datastax/cdm/cql/statement/BaseCdmStatement.java
src/main/java/com/datastax/cdm/data/CqlConversion.java
src/main/java/com/datastax/cdm/data/DataUtility.java
src/main/java/com/datastax/cdm/job/AbstractJobSession.java
src/main/java/com/datastax/cdm/job/GuardrailCheckJobSession.java
src/main/java/com/datastax/cdm/properties/KnownProperties.java
src/main/scala/com/datastax/cdm/job/BaseJob.scala
src/main/scala/com/datastax/cdm/job/ConnectionDetails.scala
src/main/scala/com/datastax/cdm/job/ConnectionFetcher.scala
src/resources/cdm-detailed.properties
src/test/java/com/datastax/cdm/cql/codec/CodecFactoryTest.java
src/test/java/com/datastax/cdm/cql/codec/TEXTFormat_InstantCodecTest.java
src/test/java/com/datastax/cdm/cql/statement/Feature_CounterTest.java
src/test/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatementTest.java
src/test/java/com/datastax/cdm/data/CqlConversionTest.java
src/test/java/com/datastax/cdm/data/DataUtilityTest.java
src/test/java/com/datastax/cdm/feature/ConstantColumnsTest.java
src/test/java/com/datastax/cdm/feature/ExtractJsonTest.java
src/test/java/com/datastax/cdm/job/ConnectionFetcherTest.java

**What this PR does**: Implements feature to connect to Astra via TLS w/o using SCB
Fixes #297 
**Checklist:**

Connect to Astra via TLS w/o using SCB

---

README.md
RELEASE.md
src/main/java/com/datastax/cdm/cql/statement/OriginSelectStatement.java
src/main/java/com/datastax/cdm/data/DataUtility.java
src/test/java/com/datastax/cdm/data/DataUtilityTest.java

**What this PR does**: Adds a static async SCB delete delay to address intermittent connection issues on spark worker nodes.
**Checklist:**

Fixed intermittent connection issues on spark worker nodes.

---

README.md
pom.xml

**What this PR does**: Update Java Driver to [`4.19.0`](https://github.com/apache/cassandra-java-driver/releases)
n/a
**Checklist:**

Update Java Driver to 4.19.0

---

Dockerfile
README.md
RELEASE.md

**What this PR does**: Update to Spark 3.5.5
n/a
**Checklist:**

Update to Spark 3.5.5

---

RELEASE.md
src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java
src/main/java/com/datastax/cdm/job/SplitPartitions.java

**What this PR does**: Randomized the pending token-range list returned by the `trackRun` feature
Fixes #352 
**Checklist:**

Randomized the pending token-range list 

---

Dockerfile
README.md
RELEASE.md
pom.xml

**What this PR does**: Upgrade Spark to `3.5.6` & Cassandra version to `5.0.4`
Fixes #366 
**Checklist:**

Upgrade Spark to 3.5.6 & Cassandra version to 5.0.4

---

.github/workflows/cdm-integrationtest.yml
.github/workflows/maven.yml

**What this PR does**: Introduces JDK 25 into the CI
n/a
**Checklist:**

Introduce JDK 25 to the CI mix
