datastax/cassandra-data-migrator

README.md, pom.xml, src/main/java/datastax/astra/migrate/DiffJobSession.java, src/main/java/datastax/astra/migrate/OriginCountJobSession.java, src/main/scala/datastax/astra/migrate/OriginData.scala
DiffData UDT fix
- Log UDT differences in readable format (instead of Java object reference). 
- If origin & target UDT's keyspace names are different, correctly perform a content based diff (do not compare keyspace names).
**Note:** Autocorrect for UDTs will not work if UDT's keyspace names are different
=> DiffData UDT fix

pom.xml, src/main/java/datastax/astra/migrate/AbstractJobSession.java, src/main/java/datastax/astra/migrate/BaseJobSession.java, src/main/java/datastax/astra/migrate/CopyJobSession.java, src/main/java/datastax/astra/migrate/DiffJobSession.java, src/main/scala/datastax/astra/migrate/AbstractJob.scala, src/main/scala/datastax/astra/migrate/BaseJob.scala, src/main/scala/datastax/astra/migrate/OriginData.scala, src/resources/sparkConf.properties
Added capability to customize `fetch-size` (fixes `FrameTooLongException`)
Use the `spark.read.fetch.sizeInRows` property to applicable value, default is `1000`
=> Added capability to customize page-size (fixes FrameTooLongException)

pom.xml, src/main/java/datastax/astra/migrate/AbstractJobSession.java, src/main/java/datastax/astra/migrate/BaseJobSession.java, src/main/java/datastax/astra/migrate/CopyJobSession.java, src/main/java/datastax/astra/migrate/CopyPKJobSession.java, src/main/java/datastax/astra/migrate/DiffJobSession.java, src/main/java/datastax/astra/migrate/OriginCountJobSession.java, src/main/java/datastax/astra/migrate/Util.java, src/resources/sparkConf.properties
- Use applicable consistency from properties (bug-fix)
- Allow separate read & write consistency (enhancement)
- Added notes/docs to properties file (docs)
- `spark.query.condition` should not require `AND` at start of condition (enhancement)
=> Use applicable read/write consistency from properties.

pom.xml, src/main/java/datastax/astra/migrate/CopyJobSession.java, src/resources/sparkConf.properties
Fixed incorrect count issue caused when retries happen due to an error. Fixes #57 
Also included error-count to report possible partition-ranges that could not be moved.
=> Fixed incorrect count issue

.gitignore, README.md, pom.xml, src/main/java/datastax/astra/migrate/DiffJobSession.java, src/main/scala/datastax/astra/migrate/DiffPartitionsFromFile.scala
**What this PR does**: Helps to re-run the DiffData from the `partitions.csv` file containing partition ranges
n/a
**Checklist:**
=> Re-run DiffData job from a file containing partition ranges

pom.xml, src/main/scala/com/datastax/cdm/job/BaseJob.scala
* Given that CDM requires users to download Apache Spark separately and submit the job, it is not necessary to bundle spark classes and shaded jars. This reduces the size of the shaded jar around 30MB.
* Currently, unnecessary tasks (10,000 tasks for default num parts) are created just to log the number of partitions. Use `getNumPartitions` instead. (Alternatively, we can remove the log line altogether since it does not add any value at all.)
Fixes CDM-84
**Checklist:**
=> [CDM-84] Improve usage of Apache Spark

README.md, src/main/java/com/datastax/cdm/properties/KnownProperties.java
**What this PR does**: This PR fixes example commands in the README file that were missing the `com.` part of class names. I'm also sneaking in a change to make target keyspace.table setting not required because Phill said it's no longer needed.
**Which issue(s) this PR fixes**: This PR does not fix any issues.
**Checklist:**
- [-] Automated Tests added/updated
- [-] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)
=> Fix class names in README examples + Make target ks.t not required

RELEASE.md, SIT/smoke/04_counters/cdm.fixData.assert, SIT/smoke/04_counters/cdm.fixForce.assert, SIT/smoke/04_counters/cdm.migrateData.assert, SIT/smoke/04_counters/cdm.validateData.assert, SIT/smoke/04_counters/expected.out, SIT/smoke/04_counters/setup.cql, pom.xml, src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java
**What this PR does**: Fixes NPE issue when there are null values in target counter tables.
Fixes #189 
**Checklist:**
=> CDM-92: Fix NPE issue with target counter tables with null fields

Dockerfile, scripts/get-latest-maven-version.sh
Automatically fetch & use the latest Maven 3 patch version for Docker builds/publish workflow
We could have simply modified the [`BASE_URL` within the `Dockerfile`](https://github.com/datastax/cassandra-data-migrator/blob/main/Dockerfile#L23) to https://archive.apache.org/dist/maven/maven-3/, but it would be more prudent to automatically fetch the latest patch version in the maven `3.9` series and use it here so we don't have to touch this script until at a point when we decide to switch using the next Maven major/minor version.
Fixes #202 
**Checklist:**
=> Use latest Maven 3 patch version for Docker workflow

src/main/java/com/datastax/cdm/feature/WritetimeTTL.java, src/resources/cdm-detailed.properties, src/test/java/com/datastax/cdm/feature/TTLAndWritetimeTest.java
Fixes ttl-writetime feature auto flag handling and some tests.
Fixes #220 
**Checklist:**
=> issue-220: Fixes ttl-writetime auto flag handling

src/main/java/com/datastax/cdm/job/SplitPartitions.java, src/test/java/com/datastax/cdm/job/SplitPartitionsTest.java
Fixes OOM exception when partition file present and numParts has a high value
Fixes #242 
**Checklist:**
=> Fix OOM issue # 242

README.md, src/resources/cdm-detailed.properties
Modifies the document associated with tokenrange. 
The tokenrange option in `--conf spark.cdm.tokenrange.partitionFile="/<path-to-file>/<csv-input-filename>"` must be in lowercase.
=> Fix tokenrange document

Dockerfile
**What this PR does**: We recently [deprecated the partition file based approach](https://github.com/datastax/cassandra-data-migrator/pull/270/commits/ceaa216f9d16027e940b1253a2748dc31bc4d045) and this is a follow-up to fix the Dockerfile.
Fixes #276
**Checklist:**
=> 276 - Remove no longer used primary_key_rows.csv file

RELEASE.md, src/main/scala/com/datastax/cdm/job/BasePartitionJob.scala
**What this PR does**: Uses origin keyspace.table property when target details are missing in the property file.
Fixes #284
**Checklist:**
=> issue 284 - Use origin ks/tbl when target property is missing

RELEASE.md, src/main/scala/com/datastax/cdm/job/BasePartitionJob.scala
**What this PR does**: Filter out empty values for target ks/tbl properties when not provided and uses origin values.
Fixes #284 
**Checklist:**
=> Use origin ks/tbl when target properties is not specified

RELEASE.md, src/main/java/com/datastax/cdm/feature/WritetimeTTL.java, src/main/java/com/datastax/cdm/properties/KnownProperties.java, src/resources/cdm-detailed.properties, src/test/java/com/datastax/cdm/feature/TTLAndWritetimeTest.java
**What this PR does**: Implemented property `spark.cdm.transform.custom.ttl` to allow a custom constant value to be set for TTL instead of using the values from origin rows.
**Checklist:**
=> Implemented customTTL feature

Dockerfile, README.md, RELEASE.md, pom.xml
**What this PR does**: Upgrades Spark to use [the latest maintenance `3.5.3` release version](https://spark.apache.org/news/spark-3-5-3-released.html).
**Checklist:**
=> Upgraded to use Spark 3.5.3

RELEASE.md, src/main/java/com/datastax/cdm/data/DataUtility.java, src/main/java/com/datastax/cdm/job/AbstractJobSession.java, src/main/scala/com/datastax/cdm/job/BaseJob.scala, src/main/scala/com/datastax/cdm/job/ConnectionFetcher.scala, src/test/java/com/datastax/cdm/data/DataUtilityTest.java
**What this PR does**: Makes SCB file much short-lived & unique to each run
Fixes #316 
**Checklist:**
=> Short-lived & unique SCB for each run

README.md, RELEASE.md, src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java, src/main/java/com/datastax/cdm/cql/statement/TargetUpsertStatement.java, src/main/java/com/datastax/cdm/data/CqlConversion.java, src/main/java/com/datastax/cdm/data/CqlData.java, src/main/java/com/datastax/cdm/data/DataUtility.java, src/main/java/com/datastax/cdm/data/EnhancedPK.java, src/main/java/com/datastax/cdm/data/PKFactory.java, src/main/java/com/datastax/cdm/feature/ExplodeMap.java, src/main/java/com/datastax/cdm/feature/WritetimeTTL.java, src/main/java/com/datastax/cdm/properties/PropertyHelper.java, src/test/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatementTest.java
**What this PR does**: Make trackRun feature work on all versions of C*
**Checklist:**
=> Make trackRun feature work on all versions of C*

src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java, src/main/java/com/datastax/cdm/feature/TrackRun.java, src/main/java/com/datastax/cdm/job/AbstractJobSession.java, src/main/java/com/datastax/cdm/job/CopyJobSession.java, src/main/java/com/datastax/cdm/job/CopyJobSessionFactory.java, src/main/java/com/datastax/cdm/job/CounterUnit.java, src/main/java/com/datastax/cdm/job/DiffJobSessionFactory.java, src/main/java/com/datastax/cdm/job/GuardrailCheckJobSession.java, src/main/java/com/datastax/cdm/job/GuardrailCheckJobSessionFactory.java, src/main/java/com/datastax/cdm/job/JobCounter.java, src/main/java/com/datastax/cdm/job/Partition.java, src/main/java/com/datastax/cdm/job/SplitPartitions.java, src/main/scala/com/datastax/cdm/job/BasePartitionJob.scala, src/test/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatementTest.java, src/test/java/com/datastax/cdm/feature/TrackRunTest.java, src/test/java/com/datastax/cdm/job/SplitPartitionsTest.java
**What this PR does**: Refactors inner classes to standard classes. These changes are in preparation for the cluster-mode metrics bug fix & since the changes are getting a lot bigger, wanted to make a smaller PR that can be reviewed easily.
**Checklist:**
=> Refactor changes #1 (in prep for cluster-metrics change)

RELEASE.md, src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java, src/main/scala/com/datastax/cdm/job/BaseJob.scala, src/main/scala/com/datastax/cdm/job/ConnectionFetcher.scala, src/main/scala/com/datastax/cdm/job/DiffData.scala, src/main/scala/com/datastax/cdm/job/GuardrailCheck.scala, src/main/scala/com/datastax/cdm/job/Migrate.scala, src/test/java/com/datastax/cdm/job/ConnectionFetcherTest.java
**What this PR does**: Fixes connection issue caused when using different types of origin and target clusters (e.g. Cassandra/DSE with host/port and Astra with SCB).
Fixes #333 
**Checklist:**
=> Fixed connection issue caused when using different types of origin and target clusters

RELEASE.md, src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java, src/main/scala/com/datastax/cdm/job/BaseJob.scala, src/main/scala/com/datastax/cdm/job/BasePartitionJob.scala, src/test/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatementTest.java
**What this PR does**: Fixes empty run issue
Fixes #335 
**Checklist:**
=> Perform fresh run when previous run not found or not-started for any reason

RELEASE.md, src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java
**What this PR does**: Converts usage of `dateOf()` to `toTimestamps()` as the `start_time` column is of CQL datatype `TIMESTAMP`.
Fixes #350 
**Checklist:**
=> Replace dateOf function with toTimestamp as it is fully removed in C* 5.0.3
